version: 2.1
workflows:
  test_app:
    jobs:
      - test_only:
          filters:
            branches:
              ignore: main
      - test_and_upload:
          filters:
            branches:
              only: main
jobs:
  test_only:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: |
            npm i -D jest-junit
            mkdir -p ~/reports
            npm test --reporters=default --reports=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
  test_and_upload:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: |
            npm i -g tap-xunit
            mkdir -p ~/reports
            npm test | tap-xunit > ~/reports/ava.xml
      - store_test_results:
          path: ~/reports
      - run:
          name: Badge Purge
          command: npx camo-purge --repository https://github.com/jchancehud/anondb
