version: 2.1
workflows:
  test_app:
    jobs:
      - test_only:
          filters:
            branches:
              ignore: main
      - test_and_upload:
          filters:
            branches:
              only: main

step_defs:
    - run: &node_version
          name: Set Node version
          command: |
              nvm install v16
              nvm alias default v16
              echo "nvm use default" >> $BASH_ENV
    - run: &check_version
          name: Check Node version
          command: node -v | grep v16

jobs:
  test_only:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: |
            npm i jest-junit
            npm test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
      - store_test_results:
          path: ./reports/
  test_and_upload:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: |
            npm i jest-junit
            npm run coverage -- --ci --runInBand --reporters=default --reporters=jest-junit
            npm run badge
      - store_test_results:
          path: ~/reports
      - run:
          name: Upload Coverage
          command: npm run upload
      - run:
          name: Badge Purge
          command: npx camo-purge --repository https://github.com/jchancehud/anondb
